const UsersList = ()=>
{
    return JSON.parse(`[
        {
          "FirstName": "Alice",
          "LastName": "Johnson",
          "PreferredName": "Ali",
          "Age": 25,
          "UserName": "alicej",
          "Email": "alice.johnson@example.com",
          "MobileNumber": "5551112222",
          "PasswordHash": "a1b2c3d4",
          "AddressLine1": "789 Oak Avenue",
          "AddressLine2": "Suite 321",
          "ZipCode": "98765",
          "City": "Chicago",
          "State": "IL",
          "Country": "USA"
        },
        {
          "FirstName": "Michael",
          "LastName": "Williams",
          "PreferredName": "Mike",
          "Age": 35,
          "UserName": "mikew",
          "Email": "michael.williams@example.com",
          "MobileNumber": "7778889999",
          "PasswordHash": "password123",
          "AddressLine1": "321 Pine Street",
          "AddressLine2": "Apt 555",
          "ZipCode": "54321",
          "City": "Houston",
          "State": "TX",
          "Country": "USA"
        },
        {
          "FirstName": "Emily",
          "LastName": "Brown",
          "PreferredName": "Em",
          "Age": 22,
          "UserName": "emilyb",
          "Email": "emily.brown@example.com",
          "MobileNumber": "9990001111",
          "PasswordHash": "qwerty",
          "AddressLine1": "987 Maple Street",
          "AddressLine2": "Unit 456",
          "ZipCode": "12345",
          "City": "San Francisco",
          "State": "CA",
          "Country": "USA"
        },
        {
          "FirstName": "Robert",
          "LastName": "Davis",
          "PreferredName": "Rob",
          "Age": 40,
          "UserName": "robertd",
          "Email": "robert.davis@example.com",
          "MobileNumber": "2223334444",
          "PasswordHash": "abcd1234",
          "AddressLine1": "654 Birch Lane",
          "AddressLine2": "Suite 789",
          "ZipCode": "67890",
          "City": "Miami",
          "State": "FL",
          "Country": "USA"
        },
        {
          "FirstName": "Jessica",
          "LastName": "Miller",
          "PreferredName": "Jess",
          "Age": 27,
          "UserName": "jessicam",
          "Email": "jessica.miller@example.com",
          "MobileNumber": "4445556666",
          "PasswordHash": "myp@ss",
          "AddressLine1": "456 Pine Street",
          "AddressLine2": "Apt 222",
          "ZipCode": "11111",
          "City": "Seattle",
          "State": "WA",
          "Country": "USA"
        },
        {
          "FirstName": "David",
          "LastName": "Lee",
          "PreferredName": "Dave",
          "Age": 33,
          "UserName": "davidl",
          "Email": "david.lee@example.com",
          "MobileNumber": "7771112222",
          "PasswordHash": "secure123",
          "AddressLine1": "789 Elm Street",
          "AddressLine2": "Suite 123",
          "ZipCode": "65432",
          "City": "Atlanta",
          "State": "GA",
          "Country": "USA"
        },
        {
          "FirstName": "Sarah",
          "LastName": "Anderson",
          "PreferredName": "Sara",
          "Age": 29,
          "UserName": "saraha",
          "Email": "sarah.anderson@example.com",
          "MobileNumber": "9998887777",
          "PasswordHash": "password1",
          "AddressLine1": "987 Oak Street",
          "AddressLine2": "Unit 567",
          "ZipCode": "34567",
          "City": "Denver",
          "State": "CO",
          "Country": "USA"
        },
        {
          "FirstName": "Daniel",
          "LastName": "Martinez",
          "PreferredName": "Dan",
          "Age": 31,
          "UserName": "danielm",
          "Email": "daniel.martinez@example.com",
          "MobileNumber": "1234567890",
          "PasswordHash": "test123",
          "AddressLine1": "654 Cedar Lane",
          "AddressLine2": "Suite 456",
          "ZipCode": "87654",
          "City": "Phoenix",
          "State": "AZ",
          "Country": "USA"
        }
      ]`)
      
}
export default UsersList